## CircleCI Config with Machine Executor and Docker Images
# Environment variables to be defined in the build configuration:
# AUTH0_TEST_CLIENT_ID = Client id to use in test
# AUTH0_TEST_DOMAIN = Domain to use in test

# Common logic
defaults: &defaults
    steps:
      - attach_workspace:
          at: ~/

      - run:
          # This could be our own script receiving the 2 values and the fullpath
          name: Replace Auth0 test credentials
          command: |
            mv $AUTH0_CFG.example $AUTH0_CFG
            sed -i 's/{CLIENT_ID}/'$AUTH0_TEST_CLIENT_ID'/g' $AUTH0_CFG
            sed -i 's/{DOMAIN}/'$AUTH0_TEST_DOMAIN'/g' $AUTH0_CFG
            sed -i 's/{API_IDENTIFIER}/'$AUTH0_TEST_API_IDENTIFIER'/g' $AUTH0_CFG

      - run:
          name: Run pull request
          command: |
            docker build -t $CIRCLE_JOB ./$SAMPLE_PATH
            docker run --network host -d -p 3000:3000 $CIRCLE_JOB

      - run:
          name: Wait for app to be available
          command: |
            sleep 10
            docker run --network host --rm appropriate/curl --retry 8 --retry-connrefused -v localhost:3000

      - run: 
          name: Run tests
          command: |
            docker create --network host --name tester codeception/codeceptjs codeceptjs run-multiple --all --steps
            docker cp $(pwd)/lock_login_test.js tester:/tests/lock_login_test.js
            docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
            docker start -i tester
            docker cp tester:/tests/out/ $(pwd)/out
            docker rm -f $(docker ps -aq)
          working_directory: scripts

      - store_artifacts:
          path: scripts/out

# Workflows
version: 2
##Job names are used as docker image tags. Must be lowercase!!
jobs: 
  checkout:
    machine: true
    steps:
      - checkout
      - run: git clone https://github.com/lbalmaceda/webapp-tests-scripts scripts
      - persist_to_workspace:
          root: ~/ 
          paths:
            - project
            - scripts

  01-login:
    machine: true
    environment:
      - AUTH0_CFG: 01-Login/src/app/auth/auth0-variables.ts
      - SAMPLE_PATH: 01-Login
    <<: *defaults

  02-user-profile:
    machine: true
    environment:
      - AUTH0_CFG: 02-User-Profile/src/app/auth/auth0-variables.ts
      - SAMPLE_PATH: 02-User-Profile
    <<: *defaults
  
  03-calling-an-api:
    machine: true
    environment:
      - AUTH0_CFG: 03-Calling-an-API/src/app/auth/auth0-variables.ts
      - SAMPLE_PATH: 03-Calling-an-API
    <<: *defaults
  
  04-authorization:
    machine: true
    environment:
      - AUTH0_CFG: 04-Authorization/src/app/auth/auth0-variables.ts
      - SAMPLE_PATH: 04-Authorization
    <<: *defaults
  
  05-token-renewal:
    machine: true
    environment:
      - AUTH0_CFG: 05-Token-Renewal/src/app/auth/auth0-variables.ts
      - SAMPLE_PATH: 05-Token-Renewal
    <<: *defaults

workflows:
  version: 2
  login_with_samples:
    jobs:
      - checkout
      - 01-login:
          requires:
            - checkout
      - 02-user-profile:
          requires:
            - checkout
      - 03-calling-an-api:
          requires:
            - checkout
      - 04-authorization:
          requires:
            - checkout
      - 05-token-renewal:
          requires:
            - checkout